"""add web session fields

Revision ID: 5a8cac04bf5e
Revises: b3c1d2e4f5a6
Create Date: 2026-06-01 10:20:09.085055
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a8cac04bf5e'
down_revision: Union[str, None] = 'b3c1d2e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('web_session_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=256), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_users_web_session_id'), 'users', ['web_session_id'], unique=True)
    op.drop_column('users', 'has_tarot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_tarot', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_web_session_id'), table_name='users')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'email')
    op.drop_column('users', 'web_session_id')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
